### ISSUE TITLE
update.txt file not available

### ISSUE THREAD

**Issue by stevellion** [mikey1234/Mikey1234#1]
Any chance we can have a sample update.txt file, in case the download version is not available.

**Comment by mikey1234** [comment]
update.txt file to what ??

**Comment by stevellion** [comment]
Mikey's karaoke.

**Comment by mikey1234** [comment]
mikeys karaoke is now completely dead and only used personally

**Comment by stevellion** [comment]
I would love to use it personally myself, but I haven't figured out how to
manage it without the update.txt file.

My kids love the YouTube karaoke search.

**Comment by mikey1234** [comment]
ok here is modified link for just using youtube version

https://www.dropbox.com/s/ul1ubjy1nuiisti/plugin.video.MikeysKaraoke.zip?dl=0

**Comment by stevellion** [comment]
Cool, thanks chap.
Much appreciated.

**Comment by mikey1234** [comment]
Please let me know once downloaded so I can remove from Dropbox


On 24 Jun 2017, at 18:07, stevellion <notifications@github.com<mailto:notifications@github.com>> wrote:

Cool, thanks chap.
Much appreciated.

**Comment by stevellion** [comment]
Done.  Cheers.
If it's just the youtube search version, is that publishable?  Leave it to
you though.
Appreciate your help.

**Comment by mikey1234** [comment]
No not at all

MikeyKaraoke is dead you said you wanted for personal use ??

developers can edit the addon if they wish and rename it to something else apart from Mikey karaoke

Thank You
Mike

On 24 Jun 2017, at 18:10, stevellion <notifications@github.com<mailto:notifications@github.com>> wrote:

Done. Cheers.
If it's just the youtube search version, is that publishable? Leave it to
you though.
Appreciate your help.

**Comment by stevellion** [comment]
I'm getting this error though : will see if I can debug over next few days.
Yes, it's just for my use, but I thought it's a cool addon and others will
like it :-)  (and just being youtube, should be clean..)
18:17:33.057 T:1519121312   ERROR: GetDirectory - Error getting

18:17:34.301 T:1961970640   ERROR: Previous line repeats 2 times.

18:17:34.302 T:1961970640   ERROR: GetDirectory - Error getting
addons://search/
18:17:34.302 T:1961970640   ERROR:
CGUIMediaWindow::GetDirectory(addons://search/) failed

18:17:38.247 T:1510732704   ERROR: Unable to lookup host: ''


18:18:11.736 T:1510732704   ERROR: GetDirectory - Error getting

18:18:12.299 T:1502344096   ERROR: Previous line repeats 6 times.

18:18:12.299 T:1502344096   ERROR: EXCEPTION Thrown (PythonToCppException)
: -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD
TO MEMORY LEAKS!
                                            Error Type: <type
'exceptions.TypeError'>
                                            Error Contents: mikeyyoutube()
takes exactly 1 argument (0 given)
                                            Traceback (most recent call
last):
                                              File
"/storage/.kodi/addons/plugin.video.MikeysKaraoke/default.py", line 745, in
<module>
                                                mikeyyoutube()

                                            TypeError: mikeyyoutube() takes
exactly 1 argument (0 given)
                                            -->End of Python script error
report<--

18:18:12.406 T:1961970640   ERROR: GetDirectory - Error getting
plugin://plugin.video.MikeysKaraoke/

18:18:12.409 T:1961970640   ERROR:
CGUIMediaWindow::GetDirectory(plugin://plugin.video.MikeysKaraoke/) failed

**Comment by mikey1234** [comment]
Out at present will send you updated when home


On 24 Jun 2017, at 18:21, stevellion <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm getting this error though : will see if I can debug over next few days.
Yes, it's just for my use, but I thought it's a cool addon and others will
like it :-) (and just being youtube, should be clean..)
18:17:33.057 T:1519121312 ERROR: GetDirectory - Error getting

18:17:34.301 T:1961970640 ERROR: Previous line repeats 2 times.

18:17:34.302 T:1961970640 ERROR: GetDirectory - Error getting
addons://search/
18:17:34.302 T:1961970640 ERROR:
CGUIMediaWindow::GetDirectory(addons://search/) failed

18:17:38.247 T:1510732704 ERROR: Unable to lookup host: ''


18:18:11.736 T:1510732704 ERROR: GetDirectory - Error getting

18:18:12.299 T:1502344096 ERROR: Previous line repeats 6 times.

18:18:12.299 T:1502344096 ERROR: EXCEPTION Thrown (PythonToCppException)
: -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD
TO MEMORY LEAKS!
Error Type: <type
'exceptions.TypeError'>
Error Contents: mikeyyoutube()
takes exactly 1 argument (0 given)
Traceback (most recent call
last):
File
"/storage/.kodi/addons/plugin.video.MikeysKaraoke/default.py", line 745, in
<module>
mikeyyoutube()

TypeError: mikeyyoutube() takes
exactly 1 argument (0 given)
-->End of Python script error
report<--

18:18:12.406 T:1961970640 ERROR: GetDirectory - Error getting
plugin://plugin.video.MikeysKaraoke/

18:18:12.409 T:1961970640 ERROR:
CGUIMediaWindow::GetDirectory(plugin://plugin.video.MikeysKaraoke/) failed

**Comment by stevellion** [comment]
Any luck with a solution on my debug log? Appreciate the help.

**Comment by mikey1234** [comment]
new plugin karaoketube will be released in noobsandnerds repo ;)



On 26 Jun 2017, at 22:05, stevellion <notifications@github.com<mailto:notifications@github.com>> wrote:


Any luck with a solution on my debug log? Appreciate the help.

**Comment by stevellion** [comment]
Great!
